import type { CMSData } from './cmsTypes';

export const defaultCMSData: CMSData = {
  banners: [],
  home: {
    heroTitle: '',
    heroSubtitle: '',
    aboutTitle: '',
    aboutDescription: '',
    statsExperience: '',
    statsEvents: '',
    statsClients: '',
    servicesTitle: '',
    servicesSubtitle: '',
    portfolioTitle: '',
    portfolioSubtitle: '',
    testimonialsTitle: '',
    testimonialsSubtitle: '',
  },
  testimonials: [],
  contact: {
    location: '',
    phone: '',
    email: '',
    facebook: '',
    instagram: '',
    tiktok: '',
    googleMap: '',
  },
  about: {
    bannerTitle: '',
    bannerSubtitle: '',
    storyTitle: '',
    storyText: '',
    missionTitle: '',
    missionText: '',
    visionTitle: '',
    visionText: '',
    teamTitle: '',
    teamText: '',
  },
  services: [],
  gallery: [],
  faqs: [],
};
